In [1]:
import numpy as np

In [2]:
print(np.version.version)

1.16.4


In [3]:
a=np.random.randint(low=0,high=10,size=(2,3,5))

In [4]:
print(a)

[[[5 3 7 7 7]
  [1 8 8 2 6]
  [9 1 3 6 9]]

 [[6 1 6 9 7]
  [0 0 4 3 9]
  [8 4 7 5 1]]]


In [5]:
b =  np.ones((5,2,3))

In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
print(a.size)
print(b.size)

if a.size == b.size:
    print(True)
else:
    print(False)

30
30
True


In [8]:
print(a.shape)
print(b.shape)

if a.shape == b.shape:
    print(a+b)
else:
    print("Not the same size")

(2, 3, 5)
(5, 2, 3)
Not the same size


In [23]:
c= np.reshape(b,(2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [24]:
d = np.add(a,c)
print(d)

[[[ 6.  4.  8.  8.  8.]
  [ 2.  9.  9.  3.  7.]
  [10.  2.  4.  7. 10.]]

 [[ 7.  2.  7. 10.  8.]
  [ 1.  1.  5.  4. 10.]
  [ 9.  5.  8.  6.  2.]]]


In [25]:
e=np.multiply(a,c)
print(e)

[[[5. 3. 7. 7. 7.]
  [1. 8. 8. 2. 6.]
  [9. 1. 3. 6. 9.]]

 [[6. 1. 6. 9. 7.]
  [0. 0. 4. 3. 9.]
  [8. 4. 7. 5. 1.]]]


In [26]:
d_max=np.max(d)
print(d_max)

d_min=np.min(d)
print(d_min)

d_mean=np.mean(d)
print(d_mean)

10.0
1.0
6.066666666666666


In [28]:
f=np.zeros((2,3,5))
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [29]:
for j in range(len(d)):
    for k in range(len(d[0])):
        for l in range(len(d[0,0])):
            if d[j,k,l] > d_min and d[j,k,l] < d_mean:
                f[j,k,l] = 25
            elif  d[j,k,l]>d_mean and d[j,k,l] < d_max:
                f[j,k,l]=75
            elif d[j,k,l] == d_mean:
                f[j,k,l]=50
            elif d[j,k,l] == d_min:
                f[j,k,l]=0
            else:
                f[j,k,l]=100
print(f)

[[[ 25.  25.  75.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [100.  25.  25.  75. 100.]]

 [[ 75.  25.  75. 100.  75.]
  [  0.   0.  25.  25. 100.]
  [ 75.  25.  75.  25.  25.]]]


In [41]:
ff=np.empty((2,3,5), dtype="object")
            
for j in range(len(d)):
    for k in range(len(d[0])):
        for l in range(len(d[0,0])):
            if d[j,k,l] > d_min and d[j,k,l] < d_mean:
                ff[j,k,l] = "l"
            elif  d[j,k,l]>d_mean and d[j,k,l] < d_max:
                ff[j,k,l]="b"
            elif d[j,k,l] == d_mean:
                ff[j,k,l]="c"
            elif d[j,k,l] == d_min:
                ff[j,k,l]="d"
            else:
                ff[j,k,l]="e"

print(ff)

[[['l' 'l' 'b' 'b' 'b']
  ['l' 'b' 'b' 'l' 'b']
  ['e' 'l' 'l' 'b' 'e']]

 [['b' 'l' 'b' 'e' 'b']
  ['d' 'd' 'l' 'l' 'e']
  ['b' 'l' 'b' 'l' 'l']]]
