In [1]:
import numpy as numpy


In [2]:
a = numpy.random.random((2,3,5))
a

array([[[0.11897008, 0.29613734, 0.47278353, 0.44220668, 0.52731243],
        [0.33351895, 0.07813552, 0.01167319, 0.09694292, 0.19686695],
        [0.94762343, 0.98095862, 0.45305536, 0.91703525, 0.80370209]],

       [[0.77801335, 0.18977725, 0.53745079, 0.71971178, 0.16821655],
        [0.12755851, 0.22525974, 0.73825694, 0.65819364, 0.00332843],
        [0.9678279 , 0.0709996 , 0.79483683, 0.27051068, 0.46819624]]])

In [3]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = numpy.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
numpy.size(a)
numpy.size(b)

30

In [1]:
#8. Are you able to add a and b? Why or why not?

#NO las matrices son de tamaño y dimensiones diferentes

print(a + b)


NameError: name 'a' is not defined

In [6]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
#Assign the transposed array to varialbe "c".

c = numpy.reshape(b, (2,3,5))
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [7]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". 
#But why does it work now?

d = numpy.add(a, c)

print(d)

[[[1.11897008 1.29613734 1.47278353 1.44220668 1.52731243]
  [1.33351895 1.07813552 1.01167319 1.09694292 1.19686695]
  [1.94762343 1.98095862 1.45305536 1.91703525 1.80370209]]

 [[1.77801335 1.18977725 1.53745079 1.71971178 1.16821655]
  [1.12755851 1.22525974 1.73825694 1.65819364 1.00332843]
  [1.9678279  1.0709996  1.79483683 1.27051068 1.46819624]]]


In [8]:
#11. Print a and d. Notice the difference and relation of the two array in terms 
#of the values? Explain.

#C es matriz de unos y a no. 

print(a)
print(d)

[[[0.11897008 0.29613734 0.47278353 0.44220668 0.52731243]
  [0.33351895 0.07813552 0.01167319 0.09694292 0.19686695]
  [0.94762343 0.98095862 0.45305536 0.91703525 0.80370209]]

 [[0.77801335 0.18977725 0.53745079 0.71971178 0.16821655]
  [0.12755851 0.22525974 0.73825694 0.65819364 0.00332843]
  [0.9678279  0.0709996  0.79483683 0.27051068 0.46819624]]]
[[[1.11897008 1.29613734 1.47278353 1.44220668 1.52731243]
  [1.33351895 1.07813552 1.01167319 1.09694292 1.19686695]
  [1.94762343 1.98095862 1.45305536 1.91703525 1.80370209]]

 [[1.77801335 1.18977725 1.53745079 1.71971178 1.16821655]
  [1.12755851 1.22525974 1.73825694 1.65819364 1.00332843]
  [1.9678279  1.0709996  1.79483683 1.27051068 1.46819624]]]


In [9]:
e = numpy.multiply(a,c)
e

#13. Does e equal to a? Why or why not?

#Sí, porque multiplicamos cada valor x 1

array([[[0.11897008, 0.29613734, 0.47278353, 0.44220668, 0.52731243],
        [0.33351895, 0.07813552, 0.01167319, 0.09694292, 0.19686695],
        [0.94762343, 0.98095862, 0.45305536, 0.91703525, 0.80370209]],

       [[0.77801335, 0.18977725, 0.53745079, 0.71971178, 0.16821655],
        [0.12755851, 0.22525974, 0.73825694, 0.65819364, 0.00332843],
        [0.9678279 , 0.0709996 , 0.79483683, 0.27051068, 0.46819624]]])

In [17]:
#14. Identify the max, min, and mean values in d. 
#Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9809586150690985
1.003328432752701
1.4465020175663816


In [19]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
#16. Populate the values in f. 
#For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding 
#value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.

f = numpy.empty([2,3,5])

# el primer elemento es la posición y e segundo es el numero o valor

for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0,0])):
            #print(d[i][j][k], d_min, d_max, d_mean)
            if d[i][j][k] > d_min and d[i][j][k] < d_mean: f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max: f[i][j][k] = 75
            elif d[i][j][k] == d_mean: f[i][j][k] = 50
            elif d[i][j][k] == d_min: f[i][j][k] = 0
            elif d[i][j][k] == d_max: f[i][j][k] = 100
print(f) 

[[[ 25.  25.  75.  25.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 75. 100.  75.  75.  75.]]

 [[ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.   0.]
  [ 75.  25.  75.  25.  75.]]]


In [70]:
print(d)

[[[1.15741396 1.57718496 1.55794585 1.75429087 1.18295349]
  [1.38785103 1.36467957 1.68662754 1.59351609 1.34470664]
  [1.09105556 1.89683448 1.75053437 1.356337   1.1626572 ]]

 [[1.88741025 1.47293087 1.36953125 1.75441738 1.32975527]
  [1.91122312 1.04106238 1.88871489 1.15340316 1.08850475]
  [1.97455596 1.88699055 1.95089172 1.18386821 1.91114982]]]


In [24]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
      #  [ 'D',  'D',  'B',  'B',  'B'],
       # [ 'D',  'B',  'D',  'D',  'D']],

     #  [[ 'B',  'B',  'B',  'B',  'E'],
      #  [ 'D',  'D',  'D',  'D',  'D'],
      #  [ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.

ff = numpy.empty([2,3,5], dtype="object")

for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0,0])):
            #print(d[i][j][k], d_min, d_max, d_mean)
            if d[i][j][k] > d_min and d[i][j][k] < d_mean: ff[i][j][k] = 'B'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max: ff[i][j][k] = 'D'
            elif d[i][j][k] == d_mean: ff[i][j][k] = 'C'
            elif d[i][j][k] == d_min: ff[i][j][k] = 'A'
            elif d[i][j][k] == d_max: ff[i][j][k] = 'E'
print(ff) 





[[['B' 'B' 'D' 'B' 'D']
  ['B' 'B' 'B' 'B' 'B']
  ['D' 'E' 'D' 'D' 'D']]

 [['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'D' 'D' 'A']
  ['D' 'B' 'D' 'B' 'D']]]
