In [14]:
import numpy as np

In [15]:
print(np.version.version)

1.17.2


In [16]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))

In [17]:
#4. Print a.

print(a)

[[[0.92598104 0.40197817 0.42482632 0.66371613 0.93045929]
  [0.13760188 0.03166089 0.0704651  0.57791757 0.4598114 ]
  [0.1690768  0.13553113 0.90339829 0.38074646 0.19877052]]

 [[0.49544784 0.60575526 0.809597   0.38395514 0.55734081]
  [0.34173021 0.80337932 0.15776063 0.02389911 0.4974305 ]
  [0.26252848 0.69824184 0.87914224 0.63275067 0.58913698]]]


In [18]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))

In [19]:
#6. Print b.

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [20]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size)
print(b.size)

30
30


In [21]:
#8. Are you able to add a and b? Why or why not?

#No se pueden agregar porque no tienen la misma forma 


In [23]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.reshape(b,(2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [24]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = np.add(a,c)
print(d)

[[[1.92598104 1.40197817 1.42482632 1.66371613 1.93045929]
  [1.13760188 1.03166089 1.0704651  1.57791757 1.4598114 ]
  [1.1690768  1.13553113 1.90339829 1.38074646 1.19877052]]

 [[1.49544784 1.60575526 1.809597   1.38395514 1.55734081]
  [1.34173021 1.80337932 1.15776063 1.02389911 1.4974305 ]
  [1.26252848 1.69824184 1.87914224 1.63275067 1.58913698]]]


In [27]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

#Los dos arreglos son iguales porque tienen la misma forma es un arreglo de 3 dimensiones con 30 elementos. 
print(a)
print(d)

[[[0.92598104 0.40197817 0.42482632 0.66371613 0.93045929]
  [0.13760188 0.03166089 0.0704651  0.57791757 0.4598114 ]
  [0.1690768  0.13553113 0.90339829 0.38074646 0.19877052]]

 [[0.49544784 0.60575526 0.809597   0.38395514 0.55734081]
  [0.34173021 0.80337932 0.15776063 0.02389911 0.4974305 ]
  [0.26252848 0.69824184 0.87914224 0.63275067 0.58913698]]]
[[[1.92598104 1.40197817 1.42482632 1.66371613 1.93045929]
  [1.13760188 1.03166089 1.0704651  1.57791757 1.4598114 ]
  [1.1690768  1.13553113 1.90339829 1.38074646 1.19877052]]

 [[1.49544784 1.60575526 1.809597   1.38395514 1.55734081]
  [1.34173021 1.80337932 1.15776063 1.02389911 1.4974305 ]
  [1.26252848 1.69824184 1.87914224 1.63275067 1.58913698]]]


In [30]:
#12. Multiply a and c. Assign the result to e.

e = np.multiply(a, c) 
print(e)

[[[0.92598104 0.40197817 0.42482632 0.66371613 0.93045929]
  [0.13760188 0.03166089 0.0704651  0.57791757 0.4598114 ]
  [0.1690768  0.13553113 0.90339829 0.38074646 0.19877052]]

 [[0.49544784 0.60575526 0.809597   0.38395514 0.55734081]
  [0.34173021 0.80337932 0.15776063 0.02389911 0.4974305 ]
  [0.26252848 0.69824184 0.87914224 0.63275067 0.58913698]]]


In [31]:
#13. Does e equal to a? Why or why not?
print(a)
print(e)

[[[0.92598104 0.40197817 0.42482632 0.66371613 0.93045929]
  [0.13760188 0.03166089 0.0704651  0.57791757 0.4598114 ]
  [0.1690768  0.13553113 0.90339829 0.38074646 0.19877052]]

 [[0.49544784 0.60575526 0.809597   0.38395514 0.55734081]
  [0.34173021 0.80337932 0.15776063 0.02389911 0.4974305 ]
  [0.26252848 0.69824184 0.87914224 0.63275067 0.58913698]]]
[[[0.92598104 0.40197817 0.42482632 0.66371613 0.93045929]
  [0.13760188 0.03166089 0.0704651  0.57791757 0.4598114 ]
  [0.1690768  0.13553113 0.90339829 0.38074646 0.19877052]]

 [[0.49544784 0.60575526 0.809597   0.38395514 0.55734081]
  [0.34173021 0.80337932 0.15776063 0.02389911 0.4974305 ]
  [0.26252848 0.69824184 0.87914224 0.63275067 0.58913698]]]


In [33]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)

print(d_min)

print(d_mean)

1.9304592859190688
1.0238991148469805
1.4716678997998724


In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty([2,3,5])

