#1. Import the NUMPY package under the name np.



#2. Print the NUMPY version and the configuration.



#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?



#4. Print a.



#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"



#6. Print b.



#7. Do a and b have the same size? How do you prove that in Python code?




#8. Are you able to add a and b? Why or why not?



#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".



#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?



#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.




#12. Multiply a and c. Assign the result to e.



#13. Does e equal to a? Why or why not?




#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"




#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.




"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""




"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np


In [2]:
#2. Print the NUMPY version and the configuration.
np.__version__

'1.16.5'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

a = np.random.random((2,3,5))
#4. Print a.
print(a)

[[[0.68715127 0.82406254 0.01507663 0.23298695 0.15778438]
  [0.74029022 0.74974046 0.51710675 0.24782055 0.10697461]
  [0.21152137 0.00535034 0.60328346 0.76696918 0.94201888]]

 [[0.8499052  0.92773377 0.61834944 0.63715533 0.23015513]
  [0.48996901 0.59130385 0.20200726 0.22436965 0.64781637]
  [0.41480577 0.48413731 0.96185469 0.14643907 0.5722567 ]]]


In [4]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.

b = np.ones((5,2,3))

#Assign the array to variable "b"

print(b)

#6. Print b.

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [5]:
#7. Do a and b have the same size? How do you prove that in Python code?

a.size == b.size, a.size,b.size

(True, 30, 30)

In [6]:
#8. Are you able to add a and b? Why or why not?
np.add(a,b) # No es posible porque tiene shapes diferentes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [7]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [8]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = sum(a,c)
d
# Funciona porque las shapes son iguales en este caso

array([[[2.53705647, 2.75179631, 1.63342607, 1.87014228, 1.38793951],
        [2.23025923, 2.34104431, 1.71911401, 1.4721902 , 1.75479098],
        [1.62632715, 1.48948765, 2.56513815, 1.91340824, 2.51427558]],

       [[2.53705647, 2.75179631, 1.63342607, 1.87014228, 1.38793951],
        [2.23025923, 2.34104431, 1.71911401, 1.4721902 , 1.75479098],
        [1.62632715, 1.48948765, 2.56513815, 1.91340824, 2.51427558]]])

In [9]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a,end="\n\n\n\n")
print(d)

[[[0.68715127 0.82406254 0.01507663 0.23298695 0.15778438]
  [0.74029022 0.74974046 0.51710675 0.24782055 0.10697461]
  [0.21152137 0.00535034 0.60328346 0.76696918 0.94201888]]

 [[0.8499052  0.92773377 0.61834944 0.63715533 0.23015513]
  [0.48996901 0.59130385 0.20200726 0.22436965 0.64781637]
  [0.41480577 0.48413731 0.96185469 0.14643907 0.5722567 ]]]



[[[2.53705647 2.75179631 1.63342607 1.87014228 1.38793951]
  [2.23025923 2.34104431 1.71911401 1.4721902  1.75479098]
  [1.62632715 1.48948765 2.56513815 1.91340824 2.51427558]]

 [[2.53705647 2.75179631 1.63342607 1.87014228 1.38793951]
  [2.23025923 2.34104431 1.71911401 1.4721902  1.75479098]
  [1.62632715 1.48948765 2.56513815 1.91340824 2.51427558]]]


In [10]:
#12. Multiply a and c. Assign the result to e.

e = np.multiply(a,c)
e

array([[[0.68715127, 0.82406254, 0.01507663, 0.23298695, 0.15778438],
        [0.74029022, 0.74974046, 0.51710675, 0.24782055, 0.10697461],
        [0.21152137, 0.00535034, 0.60328346, 0.76696918, 0.94201888]],

       [[0.8499052 , 0.92773377, 0.61834944, 0.63715533, 0.23015513],
        [0.48996901, 0.59130385, 0.20200726, 0.22436965, 0.64781637],
        [0.41480577, 0.48413731, 0.96185469, 0.14643907, 0.5722567 ]]])

In [ ]:
#13. Does e equal to a? Why or why not?
#Si porque C se esta multiplicando por 1

In [11]:
#14. Identify the max, min, and mean values in d. 
#Assign those values to variables "d_max", "d_min", and "d_mean"
d_max, d_min, d_mean = d.max(), d.min(), d.mean()

print("d_max = {}, d_min = {}, d_mean = {}".format(d_max, d_min, d_mean))

d_max = 2.7517963077043226, d_min = 1.3879395138783137, d_mean = 1.9870930760796879


In [12]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using np.empty.

f = np.empty([2,3,5])

for i,j in enumerate(f):
    print("primer nivel -> {} {}".format(i,j))
    for x,k in enumerate(j):
        print("segundo nivel-> {} {}".format(x,k))
        for counter,valor in enumerate(k):
            print("tecer nivel -> {} {}".format(counter, valor))

primer nivel -> 0 [[0.68715127 0.82406254 0.01507663 0.23298695 0.15778438]
 [0.74029022 0.74974046 0.51710675 0.24782055 0.10697461]
 [0.21152137 0.00535034 0.60328346 0.76696918 0.94201888]]
segundo nivel-> 0 [0.68715127 0.82406254 0.01507663 0.23298695 0.15778438]
tecer nivel -> 0 0.6871512700101372
tecer nivel -> 1 0.8240625368616495
tecer nivel -> 2 0.015076633250311833
tecer nivel -> 3 0.23298695055165264
tecer nivel -> 4 0.15778437990201244
segundo nivel-> 1 [0.74029022 0.74974046 0.51710675 0.24782055 0.10697461]
tecer nivel -> 0 0.740290218238114
tecer nivel -> 1 0.7497404618586336
tecer nivel -> 2 0.517106750611566
tecer nivel -> 3 0.24782054786032648
tecer nivel -> 4 0.10697461356456417
segundo nivel-> 2 [0.21152137 0.00535034 0.60328346 0.76696918 0.94201888]
tecer nivel -> 0 0.2115213749129108
tecer nivel -> 1 0.005350336674465939
tecer nivel -> 2 0.6032834614904741
tecer nivel -> 3 0.7669691778235445
tecer nivel -> 4 0.9420188785562479
primer nivel -> 1 [[0.8499052  0.927

In [13]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, 
# assign 25 to the corresponding value in f. If a value in d is larger than d_mean but smaller than d_max,
#assign 75 to the corresponding value in f. If a value equals to d_mean, 
#assign 50 to the corresponding value in f. Assign 0 to the corresponding value(s) in f for d_min in d. 
#Assign 100 to the corresponding value(s) in f for d_max in d. 
#In the end, f should have only the following values: 0, 25, 50, 75, and 100. 


#for line in data_array:
 #   result = do_stuff(line)
  #  result_array = np.append(result_array, [result], axis=0)

#3d array to list
#d2 = d.tolist()
 

for i,y in enumerate(d):
    for j,x in enumerate(y):
        for l,r in enumerate(x):
            if r > d_min and r < d_mean: f[i][j][l] = 25
            elif r > d_mean and r < d_max: f[i][j][l] = 75
            elif r == d_mean:f[i][j][l] = 50
            elif r == d_min: f[i][j][l] = 0
            elif r == d_max: f[i][j][l] = 100
           




In [14]:
f

array([[[ 75., 100.,  25.,  25.,   0.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 25.,  25.,  75.,  25.,  75.]],

       [[ 75., 100.,  25.,  25.,   0.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 25.,  25.,  75.,  25.,  75.]]])

In [16]:
#17. Print d and f. Do you have your expected f? For instance, 
#if your d is: array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

   #[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
    #[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
    #[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
#Your f should be: array([[[ 75., 75., 75., 25., 75.], [ 75., 75., 25., 25., 25.], [ 75., 25., 75., 75., 75.]],

 #  [[ 25.,  25.,  25.,  25., 100.],
  #  [ 75.,  75.,  75.,  75.,  75.],
   # [ 25.,  75.,   0.,  75.,  75.]]])
    
print(d,end="\n\n\n")
print(f)

[[[2.53705647 2.75179631 1.63342607 1.87014228 1.38793951]
  [2.23025923 2.34104431 1.71911401 1.4721902  1.75479098]
  [1.62632715 1.48948765 2.56513815 1.91340824 2.51427558]]

 [[2.53705647 2.75179631 1.63342607 1.87014228 1.38793951]
  [2.23025923 2.34104431 1.71911401 1.4721902  1.75479098]
  [1.62632715 1.48948765 2.56513815 1.91340824 2.51427558]]]


[[[ 75. 100.  25.  25.   0.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[ 75. 100.  25.  25.   0.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  75.]]]


In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), 
#how to use string values ("A", "B", "C", "D", and "E") to label the array elements? 
#You are expecting the result to be: array([[[ 'D', 'D', 'D', 'B', 'D'], [ 'D', 'D', 'B', 'B', 'B'], [ 'D', 'B', 'D', 'D', 'D']],

  # [[ 'B',  'B',  'B',  'B',  'E'],
   # [ 'D',  'D',  'D',  'D',  'D'],
    #[ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.

In [19]:
ff = np.empty([2,3,5], dtype="object")

In [20]:

for i,y in enumerate(d):
    for j,x in enumerate(y):
        for l,r in enumerate(x):
            if r > d_min and r < d_mean: ff[i][j][l] = "B"
            elif r > d_mean and r < d_max: ff[i][j][l] = "D"
            elif r == d_mean:ff[i][j][l] = "C"
            elif r == d_min: ff[i][j][l] = "A"
            elif r == d_max: ff[i][j][l] = "E"
        

In [21]:
ff

array([[['D', 'E', 'B', 'B', 'A'],
        ['D', 'D', 'B', 'B', 'B'],
        ['B', 'B', 'D', 'B', 'D']],

       [['D', 'E', 'B', 'B', 'A'],
        ['D', 'D', 'B', 'B', 'B'],
        ['B', 'B', 'D', 'B', 'D']]], dtype=object)