In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.

np.version.version

'1.16.4'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
#4. Print a.

a = np.random.random((2,3,5))
print(a)

a2 = np.random.randint(low=0, high=1000, size=(2,3,5))
print(a2)

[[[0.21147871 0.75804237 0.9115814  0.40667329 0.53182288]
  [0.98374763 0.54271426 0.88799577 0.13082761 0.55748123]
  [0.30306828 0.86861946 0.7067565  0.21372597 0.89081739]]

 [[0.8598921  0.02632583 0.90106924 0.07250084 0.03533543]
  [0.48241424 0.76747678 0.5778101  0.06510067 0.91968937]
  [0.63679283 0.01218623 0.79229505 0.21035119 0.66692815]]]
[[[258 535   2 264 689]
  [812 825 978 573 726]
  [474 378 528 917 619]]

 [[843 949 484 498 974]
  [853 905  57 592 185]
  [250 997 465 546 776]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#6. Print b.

b = np.full((5,2,3),1)
print(b)

b2 = np.ones((5,2,3))
print(b2)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
#7. Do a and b have the same size? How do you prove that in Python code?

if a.size == b.size:
    print("True")
else:
    print("False")

True


In [ ]:
#8. Are you able to add a and b? Why or why not?

Nel no son las mismas dimensiones (python no reescribre la matemática)

In [8]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.reshape(b,(2,3,5))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [9]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a+c
print(d)

[[[1.21147871 1.75804237 1.9115814  1.40667329 1.53182288]
  [1.98374763 1.54271426 1.88799577 1.13082761 1.55748123]
  [1.30306828 1.86861946 1.7067565  1.21372597 1.89081739]]

 [[1.8598921  1.02632583 1.90106924 1.07250084 1.03533543]
  [1.48241424 1.76747678 1.5778101  1.06510067 1.91968937]
  [1.63679283 1.01218623 1.79229505 1.21035119 1.66692815]]]


In [ ]:
ahora si, las dimenciones son las mismas 

In [10]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

[[[0.21147871 0.75804237 0.9115814  0.40667329 0.53182288]
  [0.98374763 0.54271426 0.88799577 0.13082761 0.55748123]
  [0.30306828 0.86861946 0.7067565  0.21372597 0.89081739]]

 [[0.8598921  0.02632583 0.90106924 0.07250084 0.03533543]
  [0.48241424 0.76747678 0.5778101  0.06510067 0.91968937]
  [0.63679283 0.01218623 0.79229505 0.21035119 0.66692815]]]
[[[1.21147871 1.75804237 1.9115814  1.40667329 1.53182288]
  [1.98374763 1.54271426 1.88799577 1.13082761 1.55748123]
  [1.30306828 1.86861946 1.7067565  1.21372597 1.89081739]]

 [[1.8598921  1.02632583 1.90106924 1.07250084 1.03533543]
  [1.48241424 1.76747678 1.5778101  1.06510067 1.91968937]
  [1.63679283 1.01218623 1.79229505 1.21035119 1.66692815]]]


In [ ]:
La matriz "d" tiene una unidad más que la "a" 

In [11]:
#12. Multiply a and c. Assign the result to e.

e = a*c
print(e)

[[[0.21147871 0.75804237 0.9115814  0.40667329 0.53182288]
  [0.98374763 0.54271426 0.88799577 0.13082761 0.55748123]
  [0.30306828 0.86861946 0.7067565  0.21372597 0.89081739]]

 [[0.8598921  0.02632583 0.90106924 0.07250084 0.03533543]
  [0.48241424 0.76747678 0.5778101  0.06510067 0.91968937]
  [0.63679283 0.01218623 0.79229505 0.21035119 0.66692815]]]


In [ ]:
#13. Does e equal to a? Why or why not?

Ps si, se multiplicó por 1 no manches

In [12]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean".

d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

1.983747626836083
1.0121862260860133
1.531050692419854


In [13]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty([2,3,5])
print(f)

[[[0.21147871 0.75804237 0.9115814  0.40667329 0.53182288]
  [0.98374763 0.54271426 0.88799577 0.13082761 0.55748123]
  [0.30306828 0.86861946 0.7067565  0.21372597 0.89081739]]

 [[0.8598921  0.02632583 0.90106924 0.07250084 0.03533543]
  [0.48241424 0.76747678 0.5778101  0.06510067 0.91968937]
  [0.63679283 0.01218623 0.79229505 0.21035119 0.66692815]]]


In [14]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
    
for i,a in enumerate(d):
    #print(i,a)
    for x,b in enumerate(a):
        #print(x,b)
        for y,c in enumerate(b):
            print(y,c)
            if c > d_min and c < d_mean:
                f[i][x][y] = 25
            elif c > d_mean and c < d_max:
                f[i][x][y] = 75
            elif c == d_mean:
                f[i][x][y] = 50
            elif c == d_min:
                f[i][x][y] = 0
            elif c == d_max:
                f[i][x][y] = 100

0 1.211478712467478
1 1.7580423654782424
2 1.9115814014272692
3 1.4066732947736849
4 1.531822879894447
0 1.983747626836083
1 1.542714256073828
2 1.887995767307331
3 1.1308276055223487
4 1.557481232506913
0 1.3030682774695825
1 1.8686194614604958
2 1.7067565011962236
3 1.2137259695321427
4 1.8908173850031273
0 1.8598921042930185
1 1.0263258309293926
2 1.9010692394796234
3 1.0725008444600972
4 1.0353354251282092
0 1.4824142400485254
1 1.7674767785449834
2 1.577810097145484
3 1.0651006683450883
4 1.9196893735647433
0 1.6367928278426498
1 1.0121862260860133
2 1.7922950482196591
3 1.2103511851073276
4 1.6669281464516108


In [15]:
#17. Print d and f. Do you have your expected f?

print(d)
print(f)

[[[1.21147871 1.75804237 1.9115814  1.40667329 1.53182288]
  [1.98374763 1.54271426 1.88799577 1.13082761 1.55748123]
  [1.30306828 1.86861946 1.7067565  1.21372597 1.89081739]]

 [[1.8598921  1.02632583 1.90106924 1.07250084 1.03533543]
  [1.48241424 1.76747678 1.5778101  1.06510067 1.91968937]
  [1.63679283 1.01218623 1.79229505 1.21035119 1.66692815]]]
[[[ 25.  75.  75.  25.  75.]
  [100.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  25.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 75.   0.  75.  25.  75.]]]


In [16]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100).
#How to use string values. ("A", "B", "C", "D", and "E") to label the array elements?

ff = np.empty([2,3,5],dtype="object")

for i,a in enumerate(d):
    #print(i,a)
    for x,b in enumerate(a):
        #print(x,b)
        for y,c in enumerate(b):
            #print(y,c)
            if c > d_min and c < d_mean:
                ff[i][x][y] = "B"
            elif c > d_mean and c < d_max:
                ff[i][x][y] = "D"
            elif c == d_mean:
                ff[i][x][y] = "C"
            elif c == d_min:
                ff[i][x][y] = "A"
            elif c == d_max:
                ff[i][x][y] = "E"
print(ff)

[[['B' 'D' 'D' 'B' 'D']
  ['E' 'D' 'D' 'B' 'D']
  ['B' 'D' 'D' 'B' 'D']]

 [['D' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['D' 'A' 'D' 'B' 'D']]]
