#### 1.- Import the NUMPY package under the name np.

In [1]:
import numpy as np

#### 2.- Print the NUMPY version and the configuration.

In [2]:
print(np.version.version)

1.21.0


#### 3.- Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a". Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find. Print a

In [3]:
# 1.-
a_1 = np.random.random((2, 3, 5))
a_1

array([[[0.17587677, 0.3813641 , 0.6251925 , 0.71451247, 0.71466546],
        [0.397129  , 0.41592668, 0.14682988, 0.56041101, 0.21933926],
        [0.59025395, 0.79489513, 0.35198264, 0.22058347, 0.03169599]],

       [[0.33371759, 0.04717761, 0.79779299, 0.3259222 , 0.99089213],
        [0.49865696, 0.23321342, 0.70795892, 0.67157786, 0.47678929],
        [0.97061393, 0.59173887, 0.20081984, 0.74445459, 0.33515286]]])

In [4]:
# 3.- 
a_2 = np.random.random(30).reshape(2, 3, 5)
a_2

array([[[0.12253001, 0.23204466, 0.05318327, 0.75305589, 0.38695835],
        [0.06507331, 0.53373402, 0.56534184, 0.96607451, 0.90444341],
        [0.08427719, 0.06198972, 0.71258041, 0.69541678, 0.09113022]],

       [[0.49985424, 0.72953171, 0.82568618, 0.28445211, 0.09408022],
        [0.55287048, 0.16976278, 0.46469315, 0.94171563, 0.02922495],
        [0.14662571, 0.38956247, 0.02650157, 0.14960273, 0.63225123]]])

#### 4.- Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable "b". Print b.

In [5]:
b = np.full((5, 2, 3), 1, dtype = int)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 5.- Do a and b have the same size? How do you prove that in Python code?

In [6]:
if a_1.shape == b.shape:
    print(True)
    print('a and b have the same size')
else:
    print(False)
    print('a and b DO NOT have the same size')
    print(f'Dimensions of a are: {a_1.shape}')
    print(f'Dimensions of b are: {b.shape}')

False
a and b DO NOT have the same size
Dimensions of a are: (2, 3, 5)
Dimensions of b are: (5, 2, 3)


#### 6.- Are you able to add a and b? Why or why not?

In [7]:
# Matrices do not have the same dimensions
c = a_1 + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 7.- Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [8]:
x = np.ones((1, 2, 3))
print(x)
print(x.shape)

y = np.transpose(x, (1, 0, 2))
print(y)
print(y.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]]
(1, 2, 3)
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)


In [9]:
c = np.transpose(b, (1, 2, 0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 8.- Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [10]:
d = a_1 + c
print(d)

[[[1.17587677 1.3813641  1.6251925  1.71451247 1.71466546]
  [1.397129   1.41592668 1.14682988 1.56041101 1.21933926]
  [1.59025395 1.79489513 1.35198264 1.22058347 1.03169599]]

 [[1.33371759 1.04717761 1.79779299 1.3259222  1.99089213]
  [1.49865696 1.23321342 1.70795892 1.67157786 1.47678929]
  [1.97061393 1.59173887 1.20081984 1.74445459 1.33515286]]]


#### 9.- Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

c was transposed into a configuration that made possible the addition of a and itself. Thus, the relation between d and a is c, is it is a "1-only" matrix, so the only difference is the ones that were added.

#### 10.- Multiply a and c. Assign the result to e.

In [11]:
e = a_1*c
print(e)

[[[0.17587677 0.3813641  0.6251925  0.71451247 0.71466546]
  [0.397129   0.41592668 0.14682988 0.56041101 0.21933926]
  [0.59025395 0.79489513 0.35198264 0.22058347 0.03169599]]

 [[0.33371759 0.04717761 0.79779299 0.3259222  0.99089213]
  [0.49865696 0.23321342 0.70795892 0.67157786 0.47678929]
  [0.97061393 0.59173887 0.20081984 0.74445459 0.33515286]]]


#### 11.- Does e equal to a? Why or why not?

Of course no. Something times one equals the number itself, which is totally different to adding 1 to a number which increases the value of that number by 1.

#### 12.- Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [12]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 13.-Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [13]:
f = np.empty([2, 3, 5])
print(f)

[[[0.17587677 0.3813641  0.6251925  0.71451247 0.71466546]
  [0.397129   0.41592668 0.14682988 0.56041101 0.21933926]
  [0.59025395 0.79489513 0.35198264 0.22058347 0.03169599]]

 [[0.33371759 0.04717761 0.79779299 0.3259222  0.99089213]
  [0.49865696 0.23321342 0.70795892 0.67157786 0.47678929]
  [0.97061393 0.59173887 0.20081984 0.74445459 0.33515286]]]


#### 14. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f. If a value equals to d_mean, assign 50 to the corresponding value in f. Assign 0 to the corresponding value(s) in f for d_min in d. Assign 100 to the corresponding value(s) in f for d_max in d. In the end, f should have only the following values: 0, 25, 50, 75, and 100. Note: you don't have to use Numpy in this question.

In [14]:
for matrix in range(d.shape[0]):
    for row in range(d.shape[1]):
        for num in range(d.shape[2]):
            x = d[matrix][row][num]
            if x > d_min and x < d_mean:
                f[matrix, row, num] = 25
            elif x > d_mean and x < d_max:
                f[matrix, row, num] = 75
            elif x == d_mean:
                f[matrix, row, num] = 50
            elif x == d_min:
                f[matrix, row, num] = 0
            elif x == d_max:
                f[matrix, row, num] = 100

In [15]:
f

array([[[ 25.,  25.,  75.,  75.,  75.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  25.,  25.,   0.]],

       [[ 25.,  25.,  75.,  25., 100.],
        [ 75.,  25.,  75.,  75.,  75.],
        [ 75.,  75.,  25.,  75.,  25.]]])

#### 15.- Print d and f. Do you have your expected f?<br>
#### For instance, if your d is:<br>
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],<br>
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],<br>
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],<br>
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],<br>
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],<br>
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])<br>
        
#### Your f should be:<br>
array([[[ 75.,  75.,  75.,  25.,  75.],<br>
        [ 75.,  75.,  25.,  25.,  25.],<br>
        [ 75.,  25.,  75.,  75.,  75.]],<br>
       [[ 25.,  25.,  25.,  25., 100.],<br>
        [ 75.,  75.,  75.,  75.,  75.],<br>
        [ 25.,  75.,   0.,  75.,  75.]]])<br>


#### 18.- Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values <br>
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:<br>
array([[[ 'D',  'D',  'D',  'B',  'D'],<br>
        [ 'D',  'D',  'B',  'B',  'B'],<br>
        [ 'D',  'B',  'D',  'D',  'D']],<br>
       [[ 'B',  'B',  'B',  'B',  'E'],<br>
        [ 'D',  'D',  'D',  'D',  'D'],<br>
        [ 'B',  'D',   'A',  'D', 'D']]])<br>

Again, you don't need Numpy in this question.<br>

In [16]:
f = np.empty((2, 3, 5)).tolist()

In [17]:
for matrix in range(d.shape[0]):
    for row in range(d.shape[1]):
        for num in range(d.shape[2]):
            x = d[matrix][row][num]
            if x > d_min and x < d_mean:
                f[matrix][row][num] = 'B'
            elif x > d_mean and x < d_max:
                f[matrix][row][num] = 'D'
            elif x == d_mean:
                f[matrix][row][num] = 'C'
            elif x == d_min:
                f[matrix][row][num] = 'A'
            elif x == d_max:
                f[matrix][row][num] = 'E'

In [18]:
f

[[['B', 'B', 'D', 'D', 'D'],
  ['B', 'B', 'B', 'D', 'B'],
  ['D', 'D', 'B', 'B', 'A']],
 [['B', 'B', 'D', 'B', 'E'],
  ['D', 'B', 'D', 'D', 'D'],
  ['D', 'D', 'B', 'D', 'B']]]