In [2]:
#1. Import the NUMPY package under the name np.

import numpy as numpy

In [3]:
#2. Print the NUMPY version and the configuration.

numpy.version.version

'1.16.5'

In [9]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
#4. Print a.

a = numpy.random.random((2,3,5))
print(a)

a2 = numpy.random.randint(low=0, high=1000, size=(2,3,5))
print(a2)

[[[0.04481475 0.38985341 0.49217271 0.49457721 0.21676157]
  [0.5156023  0.96249459 0.75039841 0.56715178 0.56133307]
  [0.79692126 0.19150764 0.16139519 0.66684117 0.48317794]]

 [[0.98375052 0.96953102 0.67860822 0.08797875 0.75146028]
  [0.24008013 0.54515745 0.89102682 0.94231445 0.67131314]
  [0.78124593 0.77789658 0.76329299 0.67676109 0.84266097]]]
[[[ 86 806 524 272 669]
  [227 394 892 153 181]
  [279 858 883  19 438]]

 [[852 581 802 387 325]
  [188  38 664 915 516]
  [438 602 401 910 106]]]


In [11]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#6. Print b.

b = numpy.full((5,2,3),1)
print(b)

b2 = numpy.ones((5,2,3))
print(b2)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
#7. Do a and b have the same size? How do you prove that in Python code?

if a.size == b.size:
    print("True")
else:
    print("False")

True


In [ ]:
#8. Are you able to add a and b? Why or why not?

It does not work because the dimensions are different.

In [20]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = numpy.reshape(b,(2,3,5))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [24]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a+c
print(d)

[[[1.04481475 1.38985341 1.49217271 1.49457721 1.21676157]
  [1.5156023  1.96249459 1.75039841 1.56715178 1.56133307]
  [1.79692126 1.19150764 1.16139519 1.66684117 1.48317794]]

 [[1.98375052 1.96953102 1.67860822 1.08797875 1.75146028]
  [1.24008013 1.54515745 1.89102682 1.94231445 1.67131314]
  [1.78124593 1.77789658 1.76329299 1.67676109 1.84266097]]]


In [ ]:
It works because the shape of the matrix is the same.

In [25]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

[[[0.04481475 0.38985341 0.49217271 0.49457721 0.21676157]
  [0.5156023  0.96249459 0.75039841 0.56715178 0.56133307]
  [0.79692126 0.19150764 0.16139519 0.66684117 0.48317794]]

 [[0.98375052 0.96953102 0.67860822 0.08797875 0.75146028]
  [0.24008013 0.54515745 0.89102682 0.94231445 0.67131314]
  [0.78124593 0.77789658 0.76329299 0.67676109 0.84266097]]]
[[[1.04481475 1.38985341 1.49217271 1.49457721 1.21676157]
  [1.5156023  1.96249459 1.75039841 1.56715178 1.56133307]
  [1.79692126 1.19150764 1.16139519 1.66684117 1.48317794]]

 [[1.98375052 1.96953102 1.67860822 1.08797875 1.75146028]
  [1.24008013 1.54515745 1.89102682 1.94231445 1.67131314]
  [1.78124593 1.77789658 1.76329299 1.67676109 1.84266097]]]


In [ ]:
The items of the matrix "d" is one unit more.

In [26]:
#12. Multiply a and c. Assign the result to e.

e = a*c
print(e)

[[[0.04481475 0.38985341 0.49217271 0.49457721 0.21676157]
  [0.5156023  0.96249459 0.75039841 0.56715178 0.56133307]
  [0.79692126 0.19150764 0.16139519 0.66684117 0.48317794]]

 [[0.98375052 0.96953102 0.67860822 0.08797875 0.75146028]
  [0.24008013 0.54515745 0.89102682 0.94231445 0.67131314]
  [0.78124593 0.77789658 0.76329299 0.67676109 0.84266097]]]


In [ ]:
#13. Does e equal to a? Why or why not?

Yes, it is equal because it is multiplied by 1.

In [96]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean".

d_max = numpy.amax(d)
print(d_max)
d_min = numpy.amin(d)
print(d_min)
d_mean = numpy.mean(d)
print(d_mean)

1.983750518868177
1.0448147498937645
1.5966027113157943


In [37]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = numpy.empty([2,3,5])
print(f)

[[[0.04481475 0.38985341 0.49217271 0.49457721 0.21676157]
  [0.5156023  0.96249459 0.75039841 0.56715178 0.56133307]
  [0.79692126 0.19150764 0.16139519 0.66684117 0.48317794]]

 [[0.98375052 0.96953102 0.67860822 0.08797875 0.75146028]
  [0.24008013 0.54515745 0.89102682 0.94231445 0.67131314]
  [0.78124593 0.77789658 0.76329299 0.67676109 0.84266097]]]


In [107]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
    
for i,a in enumerate(d):
    #print(i,a)
    for x,b in enumerate(a):
        #print(x,b)
        for y,c in enumerate(b):
            print(y,c)
            if c > d_min and c < d_mean:
                f[i][x][y] = 25
            elif c > d_mean and c < d_max:
                f[i][x][y] = 75
            elif c == d_mean:
                f[i][x][y] = 50
            elif c == d_min:
                f[i][x][y] = 0
            elif c == d_max:
                f[i][x][y] = 100
#print(f)

0 1.0448147498937645
1 1.3898534080526732
2 1.4921727080306226
3 1.4945772130914365
4 1.216761565944525
0 1.5156022998290024
1 1.9624945916975631
2 1.7503984126265975
3 1.5671517849784076
4 1.561333071601572
0 1.7969212602531952
1 1.1915076350063947
2 1.1613951923916253
3 1.6668411668239447
4 1.4831779416810331
0 1.983750518868177
1 1.969531018494684
2 1.6786082228834156
3 1.0879787464833446
4 1.7514602802143064
0 1.24008012685348
1 1.5451574469927516
2 1.8910268235125298
3 1.9423144465656903
4 1.6713131423002823
0 1.7812459253699091
1 1.7778965828219429
2 1.7632929912364417
3 1.676761090020392
4 1.8426609749541183


In [104]:
#17. Print d and f. Do you have your expected f?

print(d)
print(f)

[[[1.04481475 1.38985341 1.49217271 1.49457721 1.21676157]
  [1.5156023  1.96249459 1.75039841 1.56715178 1.56133307]
  [1.79692126 1.19150764 1.16139519 1.66684117 1.48317794]]

 [[1.98375052 1.96953102 1.67860822 1.08797875 1.75146028]
  [1.24008013 1.54515745 1.89102682 1.94231445 1.67131314]
  [1.78124593 1.77789658 1.76329299 1.67676109 1.84266097]]]
[[[  0.  25.  25.  25.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[100.  75.  75.  25.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]]]


In [111]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100).
#How to use string values. ("A", "B", "C", "D", and "E") to label the array elements?

ff = numpy.empty([2,3,5],dtype="object")

for i,a in enumerate(d):
    #print(i,a)
    for x,b in enumerate(a):
        #print(x,b)
        for y,c in enumerate(b):
            #print(y,c)
            if c > d_min and c < d_mean:
                ff[i][x][y] = "B"
            elif c > d_mean and c < d_max:
                ff[i][x][y] = "D"
            elif c == d_mean:
                ff[i][x][y] = "C"
            elif c == d_min:
                ff[i][x][y] = "A"
            elif c == d_max:
                ff[i][x][y] = "E"
print(ff)

[[['A' 'B' 'B' 'B' 'B']
  ['B' 'D' 'D' 'B' 'B']
  ['D' 'B' 'B' 'D' 'B']]

 [['E' 'D' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'D']]]
