In [1]:
import numpy as np

In [3]:
np.version.version

'1.20.3'

In [13]:
a = np.random.random((2,3,5))

In [14]:
print(a)

[[[0.15290319 0.86252378 0.14369111 0.62593143 0.46557977]
  [0.42611641 0.67286878 0.21129835 0.98118515 0.18187114]
  [0.24340859 0.25069733 0.30629432 0.846499   0.17109146]]

 [[0.73721093 0.21238022 0.9844142  0.00830514 0.29774199]
  [0.09117735 0.9664971  0.43487027 0.34456459 0.79620036]
  [0.25401979 0.1536859  0.27516926 0.4568113  0.46160592]]]


In [15]:
b = np.random.random((5,2,3))

In [16]:
print(b)

[[[0.7207888  0.34042474 0.2699991 ]
  [0.84919182 0.53897072 0.78183613]]

 [[0.88728907 0.47131866 0.21045486]
  [0.33186873 0.56843855 0.70143519]]

 [[0.28801285 0.47707646 0.05168354]
  [0.84574515 0.38123144 0.40306073]]

 [[0.46687937 0.06430843 0.71190168]
  [0.70888985 0.59771584 0.28024684]]

 [[0.73596541 0.13497674 0.77295442]
  [0.50811382 0.35956494 0.23153064]]]


In [20]:
b.size

30

In [21]:
a.size

30

In [23]:
b.size == a.size

True

In [24]:
#8
print(b+a)

ValueError: operands could not be broadcast together with shapes (5,2,3) (2,3,5) 

In [29]:
c = np.reshape(b,(2,3,5))

In [30]:
a.shape

(2, 3, 5)

In [31]:
b.shape

(5, 2, 3)

In [32]:
c.shape

(2, 3, 5)

In [34]:
d = a+c 

In [37]:
print(a)

[[[0.15290319 0.86252378 0.14369111 0.62593143 0.46557977]
  [0.42611641 0.67286878 0.21129835 0.98118515 0.18187114]
  [0.24340859 0.25069733 0.30629432 0.846499   0.17109146]]

 [[0.73721093 0.21238022 0.9844142  0.00830514 0.29774199]
  [0.09117735 0.9664971  0.43487027 0.34456459 0.79620036]
  [0.25401979 0.1536859  0.27516926 0.4568113  0.46160592]]]


In [36]:
print(d)

[[[0.87369199 1.20294852 0.4136902  1.47512324 1.00455049]
  [1.20795253 1.56015785 0.68261701 1.19164001 0.51373987]
  [0.81184714 0.95213252 0.59430717 1.32357546 0.222775  ]]

 [[1.58295608 0.59361166 1.38747493 0.47518451 0.36205042]
  [0.80307903 1.67538695 1.03258611 0.62481143 1.53216577]
  [0.38899653 0.92664032 0.78328308 0.81637624 0.69313656]]]


In [38]:
e = a*c

In [39]:
print(e)


[[[0.11021091 0.29362443 0.03879647 0.53153585 0.25093386]
  [0.3331532  0.59702911 0.09958886 0.20649518 0.06035735]
  [0.13836283 0.17584793 0.0882167  0.40384474 0.00884261]]

 [[0.62349257 0.08096602 0.39677871 0.0038775  0.01914732]
  [0.06490931 0.68513998 0.25992885 0.09656314 0.58597592]
  [0.03428676 0.1187922  0.1398173  0.16425333 0.10687591]]]


In [40]:
print(a)

[[[0.15290319 0.86252378 0.14369111 0.62593143 0.46557977]
  [0.42611641 0.67286878 0.21129835 0.98118515 0.18187114]
  [0.24340859 0.25069733 0.30629432 0.846499   0.17109146]]

 [[0.73721093 0.21238022 0.9844142  0.00830514 0.29774199]
  [0.09117735 0.9664971  0.43487027 0.34456459 0.79620036]
  [0.25401979 0.1536859  0.27516926 0.4568113  0.46160592]]]


In [42]:
d_max = d.max()
print(d_max)

1.6753869495848108


In [43]:
d_min = d.min()
print(d_min)

0.2227749997827645


In [44]:
d_mean = d.mean()
print(d_mean)

0.9236162871942855


In [51]:
f = np.empty((2,3,5))

In [52]:
print(f)

[[[0.15290319 0.86252378 0.14369111 0.62593143 0.46557977]
  [0.42611641 0.67286878 0.21129835 0.98118515 0.18187114]
  [0.24340859 0.25069733 0.30629432 0.846499   0.17109146]]

 [[0.73721093 0.21238022 0.9844142  0.00830514 0.29774199]
  [0.09117735 0.9664971  0.43487027 0.34456459 0.79620036]
  [0.25401979 0.1536859  0.27516926 0.4568113  0.46160592]]]


In [59]:
temp = []

for i in d:
    #print(i)
    for j in i:
        #print(j)
        for x in j:
            ##print(x)
            if x > d_min and x < d_mean:
                temp.append(25)
                #print("25")
            elif x > d_mean and x <d_max:
                 temp.append(75)
                #print("75")
            elif x == d_mean:
                 temp.append(50)
                #print("50")
            elif x == d_min:
                 temp.append(0)
                #print("0")
            elif x == d_max:
                 temp.append(100)
               # print("100")
               # 

f = np.reshape(temp,(2,3,5))
print(f)

[[[ 25  75  25  75  75]
  [ 75  75  25  75  25]
  [ 25  75  25  75   0]]

 [[ 75  25  75  25  25]
  [ 25 100  75  25  75]
  [ 25  75  25  25  25]]]


In [60]:
print(d)

[[[0.87369199 1.20294852 0.4136902  1.47512324 1.00455049]
  [1.20795253 1.56015785 0.68261701 1.19164001 0.51373987]
  [0.81184714 0.95213252 0.59430717 1.32357546 0.222775  ]]

 [[1.58295608 0.59361166 1.38747493 0.47518451 0.36205042]
  [0.80307903 1.67538695 1.03258611 0.62481143 1.53216577]
  [0.38899653 0.92664032 0.78328308 0.81637624 0.69313656]]]


In [61]:
temp = []

for i in d:
    #print(i)
    for j in i:
        #print(j)
        for x in j:
            ##print(x)
            if x > d_min and x < d_mean:
                temp.append('B')
                #print("25")
            elif x > d_mean and x <d_max:
                 temp.append('D')
                #print("75")
            elif x == d_mean:
                 temp.append('C')
                #print("50")
            elif x == d_min:
                 temp.append('A')
                #print("0")
            elif x == d_max:
                 temp.append('E')
               # print("100")
               # 

f = np.reshape(temp,(2,3,5))
print(f)

[[['B' 'D' 'B' 'D' 'D']
  ['D' 'D' 'B' 'D' 'B']
  ['B' 'D' 'B' 'D' 'A']]

 [['D' 'B' 'D' 'B' 'B']
  ['B' 'E' 'D' 'B' 'D']
  ['B' 'D' 'B' 'B' 'B']]]
